### ISSUE TITLE
this creates a 50MB node_modules folder... is this normal?

### ISSUE THREAD

**Issue by boltex** [angular-dashboard-framework/generator-adf-widget#2]
I am using this generator to create many different widgets. It works well but...:

Last phases of this generator are commands 'npm install & bower install'. This creates, among others, a folder named 'node_modules'  which is almost 50MB in size. Should those (mainly gulp) tools not be installed globally by npm?... and not in a folder inside this widget project folder so as not to repeat in each widget project folder? 

Or do I have some kind of problem with my npm installation? any comments or help on this would be appreciated ! thanks!

EDIT: Below are the packages that seem to be needed... what if i install each of them manually with the "-g" switch? will that keep this folder almost empty the next time I setup a new widget with this generator?

```
"gulp": "^3.8.11",
"gulp-angular-filesort": "^1.1.1",
"gulp-angular-templatecache": "^1.6.0",
"gulp-concat": "^2.5.2",
"gulp-connect": "~2.2.0",
"gulp-csslint": "^0.1.5",
"gulp-headerfooter": "^1.0.3",
"gulp-if": "^1.2.5",
"gulp-inject": "^1.2.0",
"gulp-jshint": "^1.9.4",
"gulp-less": "^3.0.2",
"gulp-load-plugins": "^0.9.0",
"gulp-minify-css": "^1.0.0",
"gulp-minify-html": "^1.0.1",
"gulp-ng-annotate": "^0.5.2",
"gulp-rename": "^1.2.0",
"gulp-replace": "^0.5.3",
"ng-annotate-adf-plugin": "^0.1.2",
"gulp-uglify": "^1.1.0",
"jshint-stylish": "^1.0.1",
"wiredep": "~2.2.2",
"del": "^1.1.1"
```

**Comment by sdorra** [comment]
You should avoid global installations as much as you can. Installing all build dependencies globally, would lead to version conflicts with other projects. It is a best practice to use local installations for each project. With this way each project can define its dependencies and can guarantee that the build will work with the defined dependencies. Please have a look at [this article of npm](https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/).

**Comment by boltex** [comment]
Again, Thank you for your concern and expertise, greatly appreciated.
