### ISSUE TITLE
Work with angular 1.4.x 

### ISSUE THREAD

**Issue by boltex** [angular-dashboard-framework/generator-adf-widget#3]
I know adf 0.11.0 works well with angular 1.4.9. 

I cannot seem to make this widget generator work with an updated angular version. 
Also, this requires adf version 0.8.0 instead of 0.11.0... 

I tried to modify the bower.json to have "angular-dashboard-framework": "0.11.0" and ran bower install.

This updated adf to 0.11.0 (and some other dependancies) so after running gulp serve again I'm getting errors: 
 knockout-sortable.js:157 Uncaught TypeError: Cannot read property 'bindingHandlers' of undefined

How can I develop new widgets with adf 0.11.0 and angular >= 1.4.9 ?
Thanks in advance!

**Comment by boltex** [comment]
Oh ! found out what the issue may be!  [THIS YEOMAN STATUS PAGE](https://www.npmjs.com/package/generator-adf-widget)
 says 0.3.2 from 10 months ago instead of 0.3.3 from 5 months ago.

**Comment by sdorra** [comment]
You're right. Version 0.3.3 should now be available through npm.
